#!/usr/bin/env bash

cd "~/.dotfiles";

function doIt() {
	rsync --exclude ".git/" \
		--exclude ".DS_Store" \
		--exclude ".osx" \
		--exclude "bootstrap.sh" \
		--exclude "README.md" \
		--exclude "LICENSE-MIT.txt" \
		--exclude "script" \
		-avh --no-perms . ~;
	source ~/.bash_profile;
}

doIt;
unset doIt;

echo "Installing google drive ..."
brew cask install google-drive
echo "Installing stow ..."
brew install stow

if [ ! -d ~/Google\ Drive/bootstrap/ ]; then
	echo " "
	echo "Sign into google drive and wait for a sync to complete, hit enter when complete"
  echo " "
	read continue
fi

cd ~/Google\ Drive/bootstrap;

# Stow symlinks directories and files, so things like Firefox profiles are synced between machines via drive
# add more directories here, but ensure that they don't exist at the target or things break (should not matter on a clean machine)
stow -t ~/Library Library

# run os x deaults script
source ~/.macos
