#!/usr/bin/env bash

cd "~/.dotfiles";

function doIt() {
	rsync --exclude ".git/" \
		--exclude ".DS_Store" \
		--exclude ".osx" \
		--exclude "bootstrap.sh" \
		--exclude "README.md" \
		--exclude "LICENSE-MIT.txt" \
		--exclude "script" \
		-avh --no-perms . ~;
	source ~/.bash_profile;
}

doIt;
unset doIt;

echo "Installing google drive ..."
brew cask install google-drive
echo "Installing stow ..."
brew install stow
echo "Installing dockutil ..."
brew install dockutil

if [ ! -d ~/Google\ Drive/bootstrap/ ]; then
	echo " "
	echo "Sign into google drive and wait for a sync to complete, hit enter when complete"
  echo " "
	read continue
fi

cd ~/Google\ Drive/bootstrap;

# Stow symlinks directories and files, so things like Firefox profiles are synced between machines via drive
# add more directories here, but ensure that they don't exist at the target or things break (should not matter on a clean machine)
stow -t ~/Library Library

# run os x deaults script
source ~/.macos

# dock management
dockutil --remove all --no-restart
dockutil --add /Applications/Launchpad.app --no-restart
dockutil --add /Applications/Firefox.app --no-restart
dockutil --add /Applications/Mail.app --no-restart
dockutil --add /Applications/Calendar.app --no-restart
dockutil --add /Applications/Messages.app --no-restart
dockutil --add ~/Applications/slack.app --no-restart
dockutil --add /Applications/Atom.app --no-restart
dockutil --add ~/Applications/geppetto.app --no-restart
dockutil --add /Applications/SourceTree.app --no-restart
dockutil --add /Applications/Virtualbox.app --no-restart
dockutil --add /Applications/iTunes.app --no-restart
dockutil --add /Applications/Utilities/Terminal.app --no-restart
dockutil --add /Applications/App\ Store.app --no-restart
dockutil --add /Applications/System\ Preferences.app
